# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks ppthat will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it ok
    - uses: actions/checkout@v2
    - name: Call Azure Pipeline
      uses: Azure/pipelines@v1
      with:
           azure-devops-project-url: 'https://dev.azure.com/MyOZ/HelloDevOps'
           azure-pipeline-name: 'DevOpsDemo-CI' 
           azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
           azure-pipeline-variables: '{"SWAGGERCHANGED": "${{ secrets.SWAGGERCHANGED }}"}'
   










        